---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build_docker_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t java8-mvn:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - push
    - tag

- name: scan-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission
  pull: always
  settings:
    image_name: java8-mvn:${DRONE_COMMIT_SHA}
    # Whitelisting CVE-2021-26291 temporarily as the recommended Maven version still contains shared-utils from vulnerable v3.2.1
    whitelist: CVE-2019-5827, CVE-2020-14363, CVE-2021-25215, CVE-2021-27219, CVE-2021-26291
  when:
    event:
    - push

- name: image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag java8-mvn:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/java8-mvn:$${DRONE_COMMIT_SHA}
  - docker tag java8-mvn:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/java8-mvn:latest
  - docker push quay.io/ukhomeofficedigital/java8-mvn:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/java8-mvn:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

- name: tagged_image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag java8-mvn:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/java8-mvn:$${DRONE_TAG}
  - docker push quay.io/ukhomeofficedigital/java8-mvn:$${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  commands:
    - /run.sh server
